name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build all projects
        id: build
        run: |
          # 创建公共目录 public
          mkdir -p public
          # 遍历所有一级目录
          for dir in */; do
            if [ -f "${dir}package.json" ]; then
              echo "Building $dir..."
              cd "$dir"
              npm install
              npm run build
              rm dist $(basename "$dir")
              cp -r "dist" "../public"
              cd ..
            fi
          done

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: public/   # 部署合并后的 public 目录
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4